# Generated by Django 4.2.1 on 2024-09-11 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Название цвета')),
                ('color', models.CharField(max_length=255, verbose_name='Цвет в hex')),
                ('rgba', models.CharField(default='0', max_length=255, verbose_name='Цвет в rgba')),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Краткое название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('priority', models.IntegerField(choices=[(1, 'first'), (2, 'second'), (3, 'third'), (4, 'fourth')], verbose_name='Приоритетность')),
                ('fileds', models.FileField(upload_to='users/%Y/%m/%d', verbose_name='Дополнительный материал')),
            ],
        ),
        migrations.CreateModel(
            name='Сategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Категория')),
                ('push', models.BooleanField(null=True, verbose_name='Уведомления')),
                ('color', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='todo.color', verbose_name='цвет')),
            ],
        ),
    ]
