# Generated by Django 4.2.1 on 2024-09-11 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_сategories_date_creat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='сategories',
            name='date_creat',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
    ]
