# Generated by Django 4.2.1 on 2024-09-12 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_сategories_date_creat'),
    ]

    operations = [
        migrations.AddField(
            model_name='сategories',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, verbose_name='Slug'),
        ),
    ]
