# Generated by Django 4.2.1 on 2024-09-16 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_works_date_tasks_works_to_warn_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.IntegerField(verbose_name='Номер приоритета')),
            ],
        ),
        migrations.AlterField(
            model_name='works',
            name='priority',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='todo.priority', verbose_name='Приоритет'),
        ),
    ]
