# Generated by Django 4.2.1 on 2024-09-17 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_priority_alter_works_priority'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilesTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файлы к задаче')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.works')),
            ],
        ),
    ]
