# Generated by Django 4.2.1 on 2024-09-17 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0009_works_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='works',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Слаг'),
        ),
    ]
